parser: babel-eslint

extends: [airbnb, plugin:react/recommended, plugin:prettier/recommended, prettier/react]

env:
  browser: true
  node: true
  jest: true
  es6: true

plugins: [react, jsx-a11y, react-hooks, prettier]

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

# settings:
#   import/resolver:
#     node:
#       extensions: [.js, .mjs]

rules:
  arrow-parens: [error, as-needed]
  no-nested-ternary: off
  react/jsx-filename-extension:
    - error
    - extensions: [.js, .jsx]
  react/jsx-props-no-spreading: off

# overrides:
#   - files: ['test/**', '**/*.spec.mjs']
#     rules:
#       # chai has function-less ".exists" and ".true" properties that trigger the
#       # no-unused-expressions rule
#       no-unused-expressions: off
#   - files: ['docs/*-wcv*.js', 'docs/*-wcv*.json']
#     rules:
#       sort-keys: error
